name: Multi-Arch Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-arm64:
    runs-on: self-hosted-arm64  # ARM64 self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show current user and hostname
        run: |
          echo "User: $(whoami)"
          echo "Hostname: $(hostname)"
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: catalogfi
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push ARM64 Image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            GHPAT=${{ secrets.GH_PAT }}
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository }}:arm64-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:arm64-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:arm64-cache,mode=max

  build-amd64:
    runs-on: self-hosted-amd64  # AMD64 self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show current user and hostname
        run: |
          echo "User: $(whoami)"
          echo "Hostname: $(hostname)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: catalogfi
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push AMD64 Image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            GHPAT=${{ secrets.GH_PAT }}
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}:amd64-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:amd64-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:amd64-cache,mode=max

  create-manifest:
    runs-on: self-hosted-amd64  # Using self-hosted-amd64 for manifest creation
    needs: [build-arm64, build-amd64]  # Ensures both builds finish first
    steps:
      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: catalogfi
          password: ${{ secrets.GH_PAT }}

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository }}:arm64-latest \
            ghcr.io/${{ github.repository }}:amd64-latest
